name: Python Test

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  django:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install ruff django
        run: |
          python -m pip install --upgrade pip
          pip install ruff django
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run ruff linter
        run: |
          ruff check --fix

      - name: Django tests
        run: |
          python manage.py migrate --noinput
          python manage.py test

      - name: Build docker Image
        run : |
          docker build -t django .

      - name: Configure AWS Credentials 1
        id: creds
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN  }}

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com
      
      - name: Tag Docker image
        run: |
          docker tag django:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com/django:latest
      
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com/django:latest

